INSERT INTO service_types (service_name, service_price) VALUES
                                                            ('Engine Diagnostics', 89.99),
                                                            ('Engine Tune-Up', 359.99),
                                                            ('Timing Belt Replacement', 299.99),
                                                            ('Oil Change', 39.99),
                                                            ('Fuel System Cleaning', 124.99),
                                                            ('Coolant Flush', 101.99),
                                                            ('Transmission Fluid Change', 145.99),
                                                            ('Tire Rotation', 29.99),
                                                            ('Tire Replacement', 659.99),
                                                            ('Brake Inspection', 39.99),
                                                            ('Brake Fluid Flush', 119.99),
                                                            ('Brake Pad Replacement', 219.99),
                                                            ('A/C System Recharge', 99.99),
                                                            ('Air Filter Replacement', 35.99),
                                                            ('Cabin Air Filter Replacement', 45.99),
                                                            ('Exhaust System Repair', 299.99),
                                                            ('Windshield Wiper Replacement', 19.99),
                                                            ('Headlight Bulb Replacement', 15.99);